const tr = {
  th: { appName:'บันทึกเพลง | Song Diary', addNew:'+ เพิ่มเพลง', edit:'แก้ไข', remove:'ลบ', lastEdited:'แก้ไขล่าสุด', home:'หน้าแรก', editor:'แก้ไขเพลง', songTitle:'ชื่อเพลง', penName:'นามปากกา', mood:'อารมณ์เพลง', section:'ท่อนเพลง', introDetail:'รายละเอียด Intro', insert:'แทรก', lyrics:'เนื้อเพลง', notes:'บันทึกเพิ่มเติม', timestamp:'วัน–เวลาบันทึก', copyLyrics:'คัดลอกเนื้อเพลง', savePDF:'บันทึกเป็น PDF', print:'พิมพ์', shareEmail:'แชร์ไปอีเมล', save:'บันทึก', cancel:'ยกเลิก', confirmDelete:'ลบบันทึกนี้หรือไม่?', language:'ภาษา', theme:'โหมดสี', light:'ครีม–น้ำตาล', dark:'ธีมสีดำ', sampleLoaded:'สร้างเพลงตัวอย่างแล้ว', updated:'บันทึกสำเร็จ', search:'ค้นหาเพลง...', instrument:'เครื่องดนตรี', type:'ประเภท', normal:'ปกติ', riff:'Riff', instrumentOnly:'Instrument' },
  en: { appName:'Song Diary', addNew:'+ Add Song', edit:'Edit', remove:'Delete', lastEdited:'Last edited', home:'Home', editor:'Edit Song', songTitle:'Song Title', penName:'Pen Name', mood:'Mood', section:'Section', introDetail:'Intro detail', insert:'Insert', lyrics:'Lyrics', notes:'Additional Notes', timestamp:'Timestamp', copyLyrics:'Copy Lyrics', savePDF:'Save as PDF', print:'Print', shareEmail:'Share via Email', save:'Save', cancel:'Cancel', confirmDelete:'Delete this note?', language:'Language', theme:'Theme', light:'Cream–Brown', dark:'Black Theme', sampleLoaded:'Sample song created', updated:'Saved', search:'Search songs...', instrument:'Instrument', type:'Type', normal:'Normal', riff:'Riff', instrumentOnly:'Instrument' }
};
export function getLang(){ return localStorage.getItem('lang') || (navigator.language?.startsWith('th') ? 'th' : 'en'); }
export function setLang(lang){ localStorage.setItem('lang', lang); }
export function t(lang,key){ return tr[lang][key] || key; }
export const SECTIONS = ['Intro','Pre-Chorus','Hook','Verse 1','Verse 2','Verse 3','Bridge','Rap','Solo','Outro'];
export const INSTRUMENTS = ['Guitar','Piano','Violin','Saxophone','Flute','Synth','Drums','Bass'];
